# Uncomment the next line to define a global platform for your project
  platform :ios, '14.0'

target 'TrackMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackMe
  pod 'KeychainSwift', '~> 19.0'
  pod "NSLogger/Swift"
  pod "TPKeyboardAvoidingSwift"

  target 'TrackMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrackMeUITests' do
    # Pods for testing
  end

end
